# $Id$
application: versapp
version: 1
runtime: python27
threadsafe: yes
api_version: 1
default_expiration: 90d
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$|
 (data/.*)|
 (PIL/.*\.so)|
 (.*/Thumbs.db)

handlers:
- url: /images
  static_dir: static/images

- url: .*
  script: main.app

builtins:
  - deferred: on
  
inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
